// <auto-generated />
using System;
using Labb3._0._1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Labb3._0._1.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    [Migration("20220201193332_Added-Data")]
    partial class AddedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Labb3._0._1.Models.Betyg", b =>
                {
                    b.Property<int>("BetygId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("BetygID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Betyg1")
                        .HasColumnName("Betyg")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("date");

                    b.Property<int>("FkElevId")
                        .HasColumnName("FK_ElevID")
                        .HasColumnType("int");

                    b.Property<int>("FkKursId")
                        .HasColumnName("FK_KursID")
                        .HasColumnType("int");

                    b.Property<int>("FkPersonalId")
                        .HasColumnName("FK_PersonalID")
                        .HasColumnType("int");

                    b.HasKey("BetygId");

                    b.HasIndex("FkElevId");

                    b.HasIndex("FkKursId");

                    b.HasIndex("FkPersonalId");

                    b.ToTable("TblBetyg");
                });

            modelBuilder.Entity("Labb3._0._1.Models.Elev", b =>
                {
                    b.Property<int>("ElevId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ElevID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Efternamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("FkGenderId")
                        .HasColumnName("FK_GenderID")
                        .HasColumnType("int");

                    b.Property<string>("Förnamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Klass")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Personnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("ElevId");

                    b.ToTable("TblElev");
                });

            modelBuilder.Entity("Labb3._0._1.Models.Kurs", b =>
                {
                    b.Property<int>("KursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("KursID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KursNamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("KursId");

                    b.ToTable("TblKurs");
                });

            modelBuilder.Entity("Labb3._0._1.Models.KursLista", b =>
                {
                    b.Property<int>("KursListaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("KursListaID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FkElevId")
                        .HasColumnName("FK_ElevID")
                        .HasColumnType("int");

                    b.Property<int>("FkKursId")
                        .HasColumnName("FK_KursID")
                        .HasColumnType("int");

                    b.HasKey("KursListaId");

                    b.HasIndex("FkElevId");

                    b.HasIndex("FkKursId");

                    b.ToTable("TblKursLista");
                });

            modelBuilder.Entity("Labb3._0._1.Models.Personal", b =>
                {
                    b.Property<int>("PersonalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PersonalID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Befattning")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("PersonalId");

                    b.ToTable("TblPersonal");
                });

            modelBuilder.Entity("Labb3._0._1.Models.Betyg", b =>
                {
                    b.HasOne("Labb3._0._1.Models.Elev", "FkElev")
                        .WithMany("Betyg")
                        .HasForeignKey("FkElevId")
                        .HasConstraintName("FK_tblBetyg_tblElev")
                        .IsRequired();

                    b.HasOne("Labb3._0._1.Models.Kurs", "FkKurs")
                        .WithMany("Betyg")
                        .HasForeignKey("FkKursId")
                        .HasConstraintName("FK_tblBetyg_tblKurs")
                        .IsRequired();

                    b.HasOne("Labb3._0._1.Models.Personal", "FkPersonal")
                        .WithMany("Betyg")
                        .HasForeignKey("FkPersonalId")
                        .HasConstraintName("FK_tblBetyg_tblPersonal")
                        .IsRequired();
                });

            modelBuilder.Entity("Labb3._0._1.Models.KursLista", b =>
                {
                    b.HasOne("Labb3._0._1.Models.Elev", "FkElev")
                        .WithMany("KursLista")
                        .HasForeignKey("FkElevId")
                        .HasConstraintName("FK_tblKursLista_tblElev")
                        .IsRequired();

                    b.HasOne("Labb3._0._1.Models.Kurs", "FkKurs")
                        .WithMany("KursLista")
                        .HasForeignKey("FkKursId")
                        .HasConstraintName("FK_tblKursLista_tblKurs")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
